### PR TITLE
Update moderator.py

### PR DESCRIPTION
**Pull request by ajmeese7**
Removed empty if with else condition and replaced it with a single if. Better stylistically and for readability. Not entirely familiar with Python but I think it will work

### CODE REVIEW

**Comment by DudeVoid** [comment]
why are you updating if you're not familiar with py

**Comment by ajmeese7** [comment]
@DudeVoid because if statements are usually very similar in most languages

**Comment by aslafy-z** [comment]
You guys need a ci (like travis) 😜

**Comment by voidpirate** [comment]
This change is invalid syntax actually.

The current way is the correct "Pythonic" way for ternary operators. The current solution reads like: if `message_number` is less than 2 print an empty string otherwise print "s". You can read more about this syntax from the link below.
https://docs.python.org/3/reference/expressions.html#conditional-expressions

**Comment by ajmeese7** [comment]
@voidpirate thanks for explaining dude. Happy New Years!

**Pull request closed without merging**
