### PR TITLE
Man it's almost 2018 but LICENSE is still 2016!!

### PR DESCRIPTION
**Pull request by DoNotSpamPls**

### CODE REVIEW

**Comment by SilBoydens** [comment]
needs to be `2016, 2017`
you need to specify every year you made changes to it, not only the current year or the year with the last changes, but all yours that changes where made

**Comment by DoNotSpamPls** [comment]
ding

**Comment by DoNotSpamPls** [comment]
added 2018

**Comment by DoNotSpamPls** [comment]
i give up

**Pull request closed without merging**
